export const REQUEST_POSTS_LIST = 'REQUEST_POSTS_LIST'
export const GET_POSTS_LIST = 'GET_POSTS_LIST'
export const GET_POSTS_LIST_FAILURE = 'GET_POSTS_LIST_FAILURE'

export const UPDATE_HEADLINE = 'UPDATE_HEADLINE'
export const GET_HEADLINE = 'GET_HEADLINE'

export const GET_POST = 'GET_POST'
export const GET_POST_FAILURE = 'GET_POST_FAILURE'
export const CLEAR_POST = 'CLEAR_POST'

export const GET_TAGS = 'GET_TAGS'
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE'

export const GET_TAG_POSTS_LIST = 'GET_TAG_POSTS_LIST'
export const GET_TAG_POSTS_LIST_FAILURE = 'GET_TAG_POSTS_LIST_FAILURE'

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE'

export const SUBMIT_RESUME = 'SUBMIT_RESUME'
export const SUBMIT_RESUME_FAILURE = 'SUBMIT_RESUME_FAILURE'

export const SUBMIT_POST = 'SUBMIT_POST'
export const SUBMIT_POST_FAILURE = 'SUBMIT_POST_FAILURE'
